# 1. [簡答題] 請問下列程式碼，運算結果分別為何？



a = np.array( [20,30,40,50] )

b = np.array( [1,2,3,4] ) 

c = 1

d = np.array( [1] )

e = np.array( [1,2] ) 

In [3]:
import numpy as np

In [6]:
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] )
c = 1
d = np.array( [1] )
e = np.array( [1,2] )
print(a+b)
print(a+c)
print(a+d)
print(a+e) #長度不同不能廣播

[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

# 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

In [18]:
c = np.ones(a.size)
for i in range(0,a.size):
    c[i] = ((a[i]+b[i])*(-a[i]/2))
print(c) # 迴圈用法
print((a+b)*(-a/2)) #Np廣播特性，可以直接計算

[ -210.  -480.  -860. -1350.]
[ -210.  -480.  -860. -1350.]


# 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

In [20]:
A = np.ones((1,6)) #1*6單位矩陣
B = np.ones((6,1)) #6*1單位矩陣

print (A * B)
print (A @ B)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[6.]]


In [2]:
import numpy as np
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,55,60])
chinese_score = np.array([65,90,82,72,66,77])

In [30]:
#1.有多少學生英文成績比數學成績高?
num=0
for i in range(0,english_score.size):
    if np.greater(english_score[i],math_score[i])==True:
        num=num+1
print("有",num,"位學生英文成績比數學高")

有 3 位學生英文成績比數學高


In [34]:
#2.是否全班同學最高分都是國文?
num=0
for i in range(0,chinese_score.size):
    if np.greater(chinese_score[i],english_score[i])==True and np.greater(chinese_score[i],math_score[i])==True :
        num=num+1
    if num==chinese_score.size:
        print("全班同學最高分都是國文")
        
ch_greater_ma = np.greater(chinese_score,math_score)
ch_greater_en = np.greater(chinese_score,english_score)
print(np.logical_and(ch_greater_ma,ch_greater_en))
print(np.logical_and(ch_greater_ma,ch_greater_en).all())

全班同學最高分都是國文
[ True  True  True  True  True  True]
True
