# [簡答題] 請問下列這三種方法有什麼不同？
print(a.sum())
print(np.sum(a))
print(sum(a)) 

In [ ]:
# sum(a)是python的內建函式，可以針對任何元素。np.sum(a) 與 a.sum() 是陣列裡的專屬函式，差別定義在 np 或 array 底下。 

# 請對一個 5x5 的隨機矩陣作正規化的操作。

In [8]:
import numpy as np
from sklearn import preprocessing #標準化模組
a = np.random.random((5,5))
print ((a-a.max()/(a.max()-a.min()))) # 最大最小值正規化

print(preprocessing.scale(a)) #標準化

[[-0.81668719 -0.64167753 -0.59774376 -0.51922442 -0.46594866]
 [-1.00517929 -0.66694659 -0.85478884 -0.09628453 -0.0757077 ]
 [-0.67109258 -0.7235966  -0.23750779 -0.29372168 -0.44383416]
 [-0.85390264 -0.11790525 -0.72542381 -0.59958218 -0.34335486]
 [-0.77900696 -0.74991117 -0.37856193 -0.87563021 -0.55626865]]
[[ 0.07801148 -0.26325665 -0.17323855 -0.15905146 -0.53835171]
 [-1.6546789  -0.37112492 -1.31683878  1.4298919   1.82414345]
 [ 1.416372   -0.61295189  1.42946061  0.68814002 -0.40447192]
 [-0.26408696  1.97261666 -0.74129038 -0.46094764  0.20382371]
 [ 0.42438238 -0.7252832   0.8019071  -1.49803283 -1.08514353]]


# 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。

In [12]:
b = np.random.random(10)
b [b.argmax()] = -1 
print(b)

[-1.          0.35767769  0.50010016  0.19237002  0.64010994  0.65388866
  0.2856505   0.34051384  0.32497839  0.77998341]


In [1]:
import numpy as np

In [14]:
#1. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])
np.savez('Hw',array1,array2)

In [28]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔
recall = np.load('Hw.npz')
print("In Hw.npz:",recall.files)
print("array1:",recall['arr_0'])
print("array2:",recall['arr_1'])

In Hw.npz: ['arr_0', 'arr_1']
array1: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
array2: [2 3 5]


In [29]:
array3 = ([[0,0,0],[1,2,3]])
np.savez('New_Hw',recall['arr_0'],recall['arr_1'],array3)
New_recall = np.load('New_Hw.npz')
print("In New_Hw.npz:",New_recall.files)
print("array1:",New_recall['arr_0'])
print("array2:",New_recall['arr_1'])
print("array3:",New_recall['arr_2'])

In New_Hw.npz: ['arr_0', 'arr_1', 'arr_2']
array1: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
array2: [2 3 5]
array3: [[0 0 0]
 [1 2 3]]
