In [9]:
import numpy as np

In [2]:
#1 0~20等差數列
array_1=np.arange(0,21,1)
print(array_1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#2.呈上題，將以上數列取出偶數。
print(array_1[::2])
for value in range(0,array_1.size):
    if array_1[value] % 2==0:
        print(array_1[value])

In [6]:
#3.呈1題，將數列取出3的倍數。
print(array_1[::3])
for value in range(0,array_1.size):
    if array_1[value] % 3==0:
        print(array_1[value])

[ 0  3  6  9 12 15 18]
0
3
6
9
12
15
18


# [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

In [16]:
a = np.random.randint(10 , size=6)

print('list(a): ', list(a))
print('tolist(): ', a.tolist())

b = np.random.randint(10 , size=6).reshape(3 , 2)

print('list(b): ', list(b))
print('tolist(): ', b.tolist())

list(a):  [7, 5, 0, 8, 0, 4]
tolist():  [7, 5, 0, 8, 0, 4]
list(b):  [array([6, 5]), array([7, 6]), array([3, 2])]
tolist():  [[6, 5], [7, 6], [3, 2]]


# 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？

a = np.random.randint(10, size=6) 

b = np.random.randint(10, size=(3,4)) 

c = np.random.randint(10, size=(2,3,2)) 

（屬性：ndim、shape、size、dtype、itemsize、length、type）

In [23]:
a = np.random.randint(10, size=6)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[8 2 2 0 9 4]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [24]:
b = np.random.randint(10, size=(3,4))
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[1 3 7 8]
 [4 1 9 0]
 [5 4 2 6]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [27]:
c = np.random.randint(10, size=(2,3,2))
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[7 9]
  [7 8]
  [8 8]]

 [[3 3]
  [5 6]
  [3 9]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


# 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。

In [36]:
#Simple

def tolist(iterable):
    if type(iterable) != np.ndarray :
        return iterable
    newlist = []
    for obj in iterable:
        newlist.append(tolist(obj))
    
    return list(newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[8, 2, 2, 0, 9, 4]
[[1, 3, 7, 8], [4, 1, 9, 0], [5, 4, 2, 6]]
[[[7, 9], [7, 8], [8, 8]], [[3, 3], [5, 6], [3, 9]]]


In [38]:
#Hard

def tolist(iterable):
    if type (iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[8, 2, 2, 0, 9, 4]
[[1, 3, 7, 8], [4, 1, 9, 0], [5, 4, 2, 6]]
[[[7, 9], [7, 8], [8, 8]], [[3, 3], [5, 6], [3, 9]]]
