In [1]:
import numpy as np

# 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

In [5]:
print(np.zeros((2, 3)))
#陣列全都是真正的0
print(np.empty((2, 3)))
#接近於0的陣列，會有數值複寫的問題

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


# 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。

In [9]:
a = np.random.rand(2, 3)
a = a * 100
print(a.round())

[[80. 46. 84.]
 [90.  7. 16.]]


# 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

In [14]:
m = 40
n = 20
a = np.random.rand(2, 3) * (m-n)
b = a
print(a)
print(b%1) #只取小數點第一位以後的數字
print((a-b%1)+n)

[[11.51246253  8.87187438 19.81389166]
 [16.29977581 18.20124181  9.91067244]]
[[0.51246253 0.87187438 0.81389166]
 [0.29977581 0.20124181 0.91067244]]
[[31. 28. 39.]
 [36. 38. 29.]]


In [15]:
#1.正常的談話的聲壓為20000微巴斯卡，請問多少分貝?
#請寫下程式
V1 = 20000
V0 = 20
decibel=20*np.log10(V1/V0)
print("分貝:",decibel)

分貝: 60.0


In [53]:
#2.30分貝的聲壓會是50分貝的幾倍?
#公式移項過後可以得到 V1 = ?
#請寫下程式
#20*log10(A/V0)=30 -> log10(A)- Log10(V0)= 3/2
#np.log10(A/20)=3/2
decibel_30=20*np.power(10,(3/2))
print("30分貝的聲壓:",decibel_30)
decibel_50=20*np.power(10,(5/2))
print("50分貝的聲壓:",decibel_50)
mutiple=(decibel_30/decibel_50)
print("30分貝的聲壓是50分貝的",'%.2f'%mutiple,"倍")

30分貝的聲壓: 632.4555320336758
50分貝的聲壓: 6324.555320336759
30分貝的聲壓是50分貝的 0.10 倍
