# 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。


In [1]:
import numpy as np
a = np.random.randint(0,100,1000000).reshape(100,100,100)

In [17]:
%timeit -n 10 a = 2
for i in a:
    for j in i:
        for k in j:
            i = i+1

25.7 ns ± 7.28 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [18]:
%timeit -n 10 a = 2
for i in a.flat:
    i = i+1

24.3 ns ± 7.28 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [19]:
%timeit -n 10 a = 2
for i in np.nditer(a):
    i = i+1

22.9 ns ± 7 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


# 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [33]:
z = np. random.randint(0,10,50)
print(z)

[7 6 8 7 0 9 6 8 3 5 9 2 8 5 7 6 8 2 8 9 6 8 2 2 3 4 2 4 8 1 3 7 7 9 6 2 1
 3 6 9 0 8 9 4 3 6 7 1 0 0]


In [35]:
rint = z [np.bincount(z).argmax()]
print('出現頻率最高的數字:',rint)
print('出現頻率最高的位置:',np.where(z==rint)[0])

出現頻率最高的數字: 3
出現頻率最高的位置: [ 8 24 30 37 44]


# 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。

In [38]:
def tolist(iterable):
    if type (iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable ]
print(tolist(z))
print(z.tolist())

[7, 6, 8, 7, 0, 9, 6, 8, 3, 5, 9, 2, 8, 5, 7, 6, 8, 2, 8, 9, 6, 8, 2, 2, 3, 4, 2, 4, 8, 1, 3, 7, 7, 9, 6, 2, 1, 3, 6, 9, 0, 8, 9, 4, 3, 6, 7, 1, 0, 0]
[7, 6, 8, 7, 0, 9, 6, 8, 3, 5, 9, 2, 8, 5, 7, 6, 8, 2, 8, 9, 6, 8, 2, 2, 3, 4, 2, 4, 8, 1, 3, 7, 7, 9, 6, 2, 1, 3, 6, 9, 0, 8, 9, 4, 3, 6, 7, 1, 0, 0]


In [4]:
#1.運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
array1_T = np.linalg.inv(array1)
print("array1的反矩陣:\n",array1_T)
ans = np.dot(array1,array1_T)
print("反矩陣成上原矩陣為單位矩陣:\n(array1_T) x (array1) = \n",ans)

array1的反矩陣:
 [[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
反矩陣成上原矩陣為單位矩陣:
(array1_T) x (array1) = 
 [[1. 0.]
 [0. 1.]]


In [5]:
#2. 運用上列array計算特徵值、特徵向量?
value, vector = np.linalg.eig(array1)
print("特徵值:",value,"\n特徵向量:\n",vector)

特徵值: [13.  2.] 
特徵向量:
 [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [7]:
#3. 運用上列array計算SVD?
array_svd = np.linalg.svd(array1)
print("SVD:\n",array_svd)

SVD:
 (array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]]), array([13.94721714,  1.86417116]), array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]]))
