In [5]:
import numpy as np

In [33]:
#1 0~20等差數列
array_1=np.arange(0,21,1)
print(array_1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [50]:
#2.呈上題，將以上數列取出偶數。
print(array_1[::2])
for value in range(0,array_1.size):
    if array_1[value] % 2==0:
        print(array_1[value])

[ 0  2  4  6  8 10 12 14 16 18 20]
0
2
4
6
8
10
12
14
16
18
20


In [54]:
#3.呈1題，將數列取出3的倍數。
print(array_1[::3])
for value in range(0,array_1.size):
    if array_1[value] % 3==0:
        print(array_1[value])

[ 0  3  6  9 12 15 18]
0
3
6
9
12
15
18
