In [2]:
import numpy as np

In [4]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
array1_T = np.linalg.inv(array1)
print("array1的反矩陣:\n",array1_T)
ans = np.dot(array1,array1_T)
print("反矩陣成上原矩陣為單位矩陣:\n(array1_T) x (array1) = \n",ans)

array1的反矩陣:
 [[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
反矩陣成上原矩陣為單位矩陣:
(array1_T) x (array1) = 
 [[1. 0.]
 [0. 1.]]


In [5]:
#2. 運用上列array計算特徵值、特徵向量?
value, vector = np.linalg.eig(array1)
print("特徵值:",value,"\n特徵向量:\n",vector)

特徵值: [13.  2.] 
特徵向量:
 [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [7]:
#3. 運用上列array計算SVD?
array_svd = np.linalg.svd(array1)
print("SVD:\n",array_svd)

SVD:
 (array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]]), array([13.94721714,  1.86417116]), array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]]))
